version: "3.9"
services:
  postgres-db:
    image: postgres:13
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 3s
      retries: 2

  migration:
    image: to_do_list_api
    command: alembic upgrade head
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - .env

  backend:
    image: to_do_list_api
    ports:
      - "8000:8000"
    depends_on:
      postgres-db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    env_file:
      - .env

  bot:
    image: to_do_list_api
    command: python bot.py
    depends_on:
      backend:
        condition: service_started
    env_file:
      - .env

volumes:
  postgres-db:

