"""add pole last_notification and change pole datetime na created_at in model To_dolist

Revision ID: 26feeaaebd16
Revises: 784bfbcaf342
Create Date: 2023-10-29 21:23:21.462428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26feeaaebd16'
down_revision = '784bfbcaf342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do_list', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('to_do_list', sa.Column('last_notification', sa.DateTime(), nullable=True))
    op.drop_column('to_do_list', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do_list', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('to_do_list', 'last_notification')
    op.drop_column('to_do_list', 'created_at')
    # ### end Alembic commands ###
