"""add pole datetime

Revision ID: 784bfbcaf342
Revises: 68dc42c60493
Create Date: 2023-10-28 19:30:01.881107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784bfbcaf342'
down_revision = '68dc42c60493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do_list', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('to_do_list', 'datetime')
    # ### end Alembic commands ###
