"""add in model User pole user_id

Revision ID: 7e1c33dbaa09
Revises: 90c6913546e6
Create Date: 2023-10-18 13:25:25.491593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1c33dbaa09'
down_revision = '90c6913546e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
