"""change model To_do_list: pole name unique

Revision ID: 90c6913546e6
Revises: cef0694e4bb9
Create Date: 2023-10-13 00:05:11.315055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c6913546e6'
down_revision = 'cef0694e4bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('to_do_list_name_key', 'to_do_list', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('to_do_list_name_key', 'to_do_list', ['name'])
    # ### end Alembic commands ###
