"""change to_do_list in project on task

Revision ID: b685d8ac0db1
Revises: 973e718d1e36
Create Date: 2023-10-30 11:45:50.386790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b685d8ac0db1'
down_revision = '973e718d1e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
